### ISSUE TITLE
Lack of symlink validation can allow accessing files outside the html folder.

### ISSUE THREAD

**Issue by DEMON1A** [Praudyogikee/SimplyJServer#3]
- During a cool source review process. i noticed that simplyJServer doesn't validate the files if they're a symlink files or not. that gives a chance for malicious users to read files outside the HTML folder using a symlink inside of the public_html folder that points into other files inside of the system.

- On `API.java` you're using `readFile` function with the following code.

```java
public static byte[] readFile(String filename, boolean ispublic) {
		byte[] out = null;
		try {
			filename = Filenamer(filename, ispublic);
			File f = new File(filename);
			FileInputStream m = new FileInputStream(f);
			try {
				out = m.readAllBytes();
			} catch (Exception ee) {
				out = "404FILENOTFOUND".getBytes();
			}
			m.close();
		} catch (Exception e) {
			out = "404FILENOTFOUND".getBytes();
		}
		return out;
	}
```

- That's getting the filename, then requesting the file from the `public_html` folder after that. so if the file is a symlink it won't detect it and it will read the file in all cases even if it's outside the `public_html`.

- You should be adding a second layer of symlink validation into the code after getting the filename from the `Filenamer` function. the fix should be something **like this**:

```java
[...]
boolean isSymbolicLink = Files.isSymbolicLink(filename);

if (isSumbolicLink){
    out = "404FILENOTFOUND".getBytes();
    return out;
}

[...]
```

**Comment by Zelakolase** [comment]
Solved!
