### ISSUE TITLE
Public html files existence enumeration when the extension isn't supported.

### ISSUE THREAD

**Issue by DEMON1A** [Praudyogikee/SimplyJServer#5]
- On simplyJServer there's an allowed extensions for users stored on `.ct` file if you're running the server with the default configurations. you can store any files inside of your `public_html` folder. but if the file extension doesn't exists. the server will return `901` error while requesting it.

- In this case. users are aware of the files inside `public_html` couldn't be served to public when it's extension isn't allowed. but in this case. remote attackers can detect if a file with unallowed extension exists on the `public_html` folder using timing detection.

- So, if you have a file called `test.ht` inside your `public_html` folder. and you tried to access it from the web-server using `/test.ht`. the server will return `901` error on the output. but if you visited some file with unallowed extension that doesn't exists like `testhere.ht`. the server won't response to you and will keep loading without doing anything. that's because it's trying to send a `Null` value on the response that could be the `type` or the `res`. didn't really do a full debug since it requires building the application over again to edit the code every time.

- This issue can allow remote users to confirm the existence of files with unallowed extensions that won't be served inside simplyJServer.

**Comment by Zelakolase** [comment]
The confirmation itself doesn't help with anything. However, I edited the code so "127.0.0.1//restricted.ht" will be blocked since it's a hacking attempt.
Also, Yes, type returns null because .ht doesn't exist in the hashmap. I also edited it.
